In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [62]:
points = pd.read_csv('new.csv')
labels = pd.read_csv('label.csv')
points.head()

Unnamed: 0   V1   V2   V3   V4   V5   V6   V7   V8   V9  ...  V147  V148  \
0           1  457  412  429  451  473  494  479  456  432  ...   638   666   
1           2  465  421  438  460  484  501  485  463  441  ...   628   658   
2           3  362  320  338  359  380  395  377  357  339  ...   630   664   
3           4  424  377  397  417  439  455  437  416  395  ...   639   672   
4           5  454  419  432  453  473  490  473  454  436  ...   605   632   

   V149  V150  V151  V152  V153  V154  V155  V156  
0   681   664   638   602   547   491   434   377  
1   671   660   626   586   533   475   417   358  
2   676   663   629   591   542   489   435   380  
3   688   672   637   600   548   488   427   366  
4   645   634   604   568   518   466   411   357  

[5 rows x 157 columns]

In [63]:
labels.head()

Unnamed: 0  Index  identity  emotion_idx emotion_cat    type
0           1      1       111            1     Neutral  simple
1           2      2       114            1     Neutral  simple
2           3      3       115            1     Neutral  simple
3           4      4       116            1     Neutral  simple
4           5      5       117            1     Neutral  simple

In [64]:
labels.shape

(2500, 6)

In [65]:
points.shape

(2500, 157)

In [66]:
X = points.iloc[:, 1:157].values
y = labels.iloc[:, 3].values

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [140]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [73]:
y_pred = classifier.predict(X_test)

In [74]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.158


In [75]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 6  1  1  3  0  1  0  0  0  2  2  0  1  0  0  2  1  0  1  0  0  1]
 [ 0 10  2  0  2  1  2  4  2  1  0  1  0  1  0  0  0  0  1  0  0  0]
 [ 0  0  2  2  1  2  0  2  1  1  1  3  1  0  1  2  1  0  0  0  2  3]
 [ 1  1  2  4  0  1  0  0  0  4  2  2 12  1  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  4  0  2  3  1  0  1  1  1  2  2  0  1  1  1  2  3  0]
 [ 4  0  1  0  0  5  0  0  2  0  1  3  4  0  0  0  0  0  0  1  1  1]
 [ 0  1  1  0  2  0  5  1  1  0  0  0  1  2  1  0  1  0  2  0  0  2]
 [ 0  4  0  0  2  0  5  7  1  1  0  0  0  1  1  0  3  2  0  0  0  0]
 [ 0  7  0  1  1  0  0  2  2  0  0  1  0  0  1  1  2  1  0  1  1  0]
 [ 1  0  1  3  0  1  0  0  0  4  6  1  2  0  0  0  0  0  0  2  0  0]
 [ 2  0  2  2  0  0  0  0  0  2  3  2  3  1  0  2  0  0  0  2  0  2]
 [ 0  1  1  2  0  0  1  0  1  0  1  1  3  1  0  0  1  0  0  0  0  3]
 [ 3  0  2  2  0  0  0  0  0  3  1  3  4  0  0  1  0  0  1  0  1  2]
 [ 0  1  0  0  1  0  0  0  0  2  1  0  0  3  3  0  0  0  2  2  1  0]
 [ 0  0  1  0  2  0  0  1  0  0  1

In [76]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 5.972
Mean Squared Error: 62.852
Root Mean Squared Error: 7.927925327599901


In [83]:
# cross validation with k=5
from sklearn.model_selection import cross_val_score
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
scores = cross_val_score(classifier, X_train, y_train, cv = 5)
print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),
                                          scores.std()),
                                          end="\n\n" )

mean: 0.136 (std: 0.010)



In [142]:
# changing parameters using GridSearch
from sklearn.model_selection import GridSearchCV
#create new a knn model
dt2 = DecisionTreeClassifier()
#create a dictionary of all values we want to test for n_neighbors
param_grid = {"criterion": ["gini", "entropy"],
              "min_samples_split": [2, 10, 20],
              "max_depth": [None, 2, 5, 10],
              "min_samples_leaf": [1, 5, 10],
              "max_leaf_nodes": [None, 5, 10, 20],
              }
#use gridsearch to test all values for n_neighbors
dt_gscv = GridSearchCV(dt2, param_grid, cv=5)
#fit model to data
dt_gscv.fit(X_train, y_train)

/Users/mingming/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 2, 5, 10],
                     

In [143]:
dt_gscv.best_params_

{'criterion': 'gini',
 'max_depth': None,
 'max_leaf_nodes': None,
 'min_samples_leaf': 10,
 'min_samples_split': 10}

In [144]:
dt_gscv.best_score_

0.1645